package com.chernyee.cssquare.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.chernyee.cssquare.model.Note;
import com.chernyee.cssquare.model.Question;

import com.chernyee.cssquare.model.NoteDao;
import com.chernyee.cssquare.model.QuestionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig noteDaoConfig;
    private final DaoConfig questionDaoConfig;

    private final NoteDao noteDao;
    private final QuestionDao questionDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        questionDaoConfig = daoConfigMap.get(QuestionDao.class).clone();
        questionDaoConfig.initIdentityScope(type);

        noteDao = new NoteDao(noteDaoConfig, this);
        questionDao = new QuestionDao(questionDaoConfig, this);

        registerDao(Note.class, noteDao);
        registerDao(Question.class, questionDao);
    }
    
    public void clear() {
        noteDaoConfig.getIdentityScope().clear();
        questionDaoConfig.getIdentityScope().clear();
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

    public QuestionDao getQuestionDao() {
        return questionDao;
    }

}
